### model
model_name_or_path: meta-llama/Llama-3.2-11B-Vision-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: mllm_reasoning
template: mllama
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/mulberry_llama_11b/full/sft_epoch2_lr1e-5_warm003
logging_steps: 10
save_steps: 9999
save_only_model: true
save_strategy: 'no'
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0
per_device_eval_batch_size: 1
eval_strategy: 'no'
eval_steps: 10000000
